# Generated by Django 5.2.5 on 2025-08-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedproduct',
            old_name='requested_quanity',
            new_name='requested_quantity',
        ),
        migrations.RenameField(
            model_name='requestedproduct',
            old_name='Reservation',
            new_name='reservation',
        ),
    ]
